name: "scylla"

services:
  scylla:
    image: scylladb/scylla:latest
    container_name: scylla
    platform: linux/arm64/v8  # Adicione isso se estiver usando ARM, ajuste conforme necessário
    ports:
      - "9042:9042"  # Porta do CQL
      - "9160:9160"  # Porta do Thrift
    environment:
      - SCYLLA_RPC_ADDRESS=0.0.0.0  # Configure o rpc_address para aceitar conexões de qualquer interface
      - SCYLLA_LISTEN_ADDRESS=0.0.0.0  # Define o listen_address para o ScyllaDB aceitar conexões de qualquer interface
      - SCYLLA_BROADCAST_ADDRESS=localhost  # (Opcional) Define o endereço de broadcast
      - SCYLLA_BROADCAST_RPC_ADDRESS=localhost  # (Opcional) Define o endereço de RPC para broadcast
      - SCYLLA_AUTHENTICATION_ENABLED=true  # Habilita a autenticação
      - SCYLLA_USERNAME=admin  # Nome de usuário
      - SCYLLA_PASSWORD=password123  # Senha para o usuário admin
    volumes:
      - scylla-data:/var/lib/scylla  # Persistência de dados do ScyllaDB
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh  # Volume que mapeia o script de inicialização
#    entrypoint: [ "/bin/bash", "/docker-entrypoint-initdb.d/init.sh" ]  # Executa o script de inicialização


volumes:
  scylla-data:

# docker exec -it scylla cqlsh -u admin -p password123
# CREATE KEYSPACE meubanco WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};