name: api

volumes:

  postgres_volume:

networks:

  api_network:
    name: api_network
    driver: bridge

services:

  postgres:

    hostname: postgres
    container_name: api_postgres
    image: postgres:14.7-alpine
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./build/postgreSQL:/docker-entrypoint-initdb.d
    command: -p ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - TZ=${TZ}
      - POSTGRES_DB=${POSTGRES_BASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
    networks:
      - api_network
    profiles: [ all, services ]

  backend_binary:

    container_name: api_backend_binary
    build:
      context: .
      dockerfile: ./build/package/binary.Dockerfile
    image: api_backend_binary
    restart: always
    depends_on:
      - postgres
    ports:
      - ${API_PORT}:${API_PORT}
    tty: true
    environment:
      - TZ=${TZ}
    networks:
      - api_network
    profiles: [ all, binary ]

  backend_source:

    container_name: api_backend_source
    build:
      context: .
      dockerfile: ./build/package/source.Dockerfile
    image: api_backend_source
    restart: always
    depends_on:
      - postgres
    ports:
      - ${API_PORT}:${API_PORT}
    tty: true
    environment:
      - TZ=${TZ}
    networks:
      - api_network
    profiles: [ all, source ]
