name: go_api

volumes:

  go_api_postgres_volume:
    name: go_api_postgres_volume
  go_api_minio_volume:
    name: go_api_minio_volume

networks:

  go_api_network:
    name: go_api_network
    driver: bridge

services:

  postgres:

    hostname: postgres
    container_name: go_api_postgres
    image: postgres:14.7-alpine
    restart: always
    volumes:
      - go_api_postgres_volume:/var/lib/postgresql/data
    command: -p ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - TZ=${TZ}
      - POSTGRES_DB=${POSTGRES_BASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
    networks:
      - go_api_network

  minio:

    hostname: minio
    container_name: go_api_minio
    image: bitnami/minio:2024
    restart: always
    volumes:
      - go_api_minio_volume:/bitnami/minio/data
    ports:
      - ${MINIO_API_PORT}:${MINIO_API_PORT}
      - ${MINIO_WEB_PORT}:${MINIO_WEB_PORT}
    environment:
      - TZ=${TZ}
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASS}
      - MINIO_API_PORT_NUMBER=${MINIO_API_PORT}
      - MINIO_CONSOLE_PORT_NUMBER=${MINIO_WEB_PORT}
    networks:
      - go_api_network

  backend:

    container_name: go_api_backend
    build: .
    image: go_api_backend
    restart: always
    depends_on:
      - postgres
    ports:
      - ${API_PORT}:${API_PORT}
    tty: true
    environment:
      - TZ=${TZ}
    networks:
      - go_api_network