name: Go API Backend Build

on:
  pull_request:
    branches: [ "main" ]

jobs:
  Build:
    runs-on: [ ubuntu-latest ]

    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Get build version
        id: getVersion
        run: echo "version=$(cat configs/version.txt)" >> $GITHUB_OUTPUT

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Environment file
        run: make init

      - name: Remove object and cached files
        run: go clean -modcache

      - name: Build
        run: make build

      - name: Copy README.md
        run: cp .github/README.md README.md

      - uses: actions/upload-artifact@v4
        with:
          name: go_api_${{ steps.getVersion.outputs.version }}
          path: |
            configs/.env
            backend
            README.md
            Makefile
            api/
            build/
          if-no-files-found: error
          overwrite: true
          include-hidden-files: true
