name: Go API Backend Unit Tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  Test:
    name: Golang api_test

    runs-on: [ ubuntu-latest ]

    steps:
      - name: Fetch Repository
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"
          cache: false

      - name: Environment file
        run: make init

      - name: Run Test
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          timeout_minutes: 15
          command: go test ./...
